In [24]:
from sklearn import linear_model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns

%matplotlib inline
matplotlib.style.use('ggplot')

In [25]:
happy_raw = pd.read_csv('total_raw.csv', engine='python')
happy_raw.head()

happy_raw.drop(happy_raw['No'],axis=1)

# happy_raw = happy_raw.drop([happy_raw["No"]],axis=1)

KeyError: '[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27\n 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51\n 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75\n 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99\n 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117\n 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135\n 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153\n 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171\n 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189\n 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207\n 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225\n 226 227 228 229] not found in axis'

In [26]:
happy_mean = pd.read_csv('total_raw_mean.csv', engine='python')
happy_mean.head()

,No,city,city2,hp1,hp2,h_mean,e_mean,s_mean,ed_mean,sf_mean,l_mean,en_mean,hp3
0,1,서울특별시,종로구,a,0.8074,0.9220,1.0000,0.7425,0.6839,0.7470,0.6331,0.4637,0.4437
1,2,서울특별시,중구,a,0.6939,0.6742,0.9806,0.4608,0.5013,0.9320,0.6691,0.2865,0.4976
2,3,서울특별시,용산구,a,0.5310,0.5898,0.6915,0.4317,0.2679,0.5537,0.2817,0.5030,0.6161
3,4,서울특별시,성동구,c,0.4751,0.4794,0.6533,0.4182,0.2464,0.5347,0.3257,0.4196,0.4729
4,5,서울특별시,광진구,b,0.5317,0.6373,0.4445,0.3519,0.4879,0.6072,0.3313,0.4992,0.4041

In [27]:
happy_mean.corr()

,No,hp2,h_mean,e_mean,s_mean,ed_mean,sf_mean,l_mean,en_mean,hp3
No,1.000000,-0.259745,-0.426057,-0.386646,-0.005574,-0.046170,0.134689,0.541240,0.435929,0.171025
hp2,-0.259745,1.000000,0.759424,0.407979,0.295748,0.285682,0.349784,0.120935,-0.028138,0.162068
h_mean,-0.426057,0.759424,1.000000,0.114538,-0.046839,0.073462,0.072074,-0.188348,-0.111183,0.026245
e_mean,-0.386646,0.407979,0.114538,1.000000,0.169831,0.309088,-0.122238,-0.225453,-0.611276,-0.142599
s_mean,-0.005574,0.295748,-0.046839,0.169831,1.000000,0.300210,-0.111576,0.078624,0.057479,0.166957
ed_mean,-0.046170,0.285682,0.073462,0.309088,0.300210,1.000000,-0.398131,-0.211439,-0.246892,-0.094089
sf_mean,0.134689,0.349784,0.072074,-0.122238,-0.111576,-0.398131,1.000000,0.433283,0.254177,0.198159
l_mean,0.541240,0.120935,-0.188348,-0.225453,0.078624,-0.211439,0.433283,1.000000,0.391609,0.297341
en_mean,0.435929,-0.028138,-0.111183,-0.611276,0.057479,-0.246892,0.254177,0.391609,1.000000,0.373177
hp3,0.171025,0.162068,0.026245,-0.142599,0.166957,-0.094089,0.198159,0.297341,0.373177,1.000000